services:
  nginx:
    image: nginx:1.28.2
    ports:
      - '81:80'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/templates/default.conf.template:ro'
      - './src:/var/www/${PROJECT_NAME}'
    depends_on:
      php:
        condition: service_started
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME}
    volumes:
      - './src:/var/www/${PROJECT_NAME}'
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  composer:
    profiles: ["tools"]
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME}
    volumes:
      - './src:/var/www/${PROJECT_NAME}'
  artisan:
    profiles: ["tools"]
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME}
    volumes:
      - './src:/var/www/${PROJECT_NAME}'
    entrypoint:
      - php
      - /var/www/${PROJECT_NAME}/artisan
  npm:
    image: node:20.19.5-bullseye
    working_dir: /var/www/${PROJECT_NAME}
    entrypoint: ["npm"]
    volumes:
      - './src:/var/www/${PROJECT_NAME}'
  telegram-bot:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME}
    volumes:
      - './src:/var/www/${PROJECT_NAME}'
    command: php artisan telegram:polling
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
  scheduler:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME}
    volumes:
      - './src:/var/www/${PROJECT_NAME}'
    command: sh -c "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"
    restart: unless-stopped
